<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="M5-L-CNM8103" failures="1" tests="8" name="Default test" time="2.132" errors="0" timestamp="2021-08-16T00:52:22 IST">
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="ListsAllCustomerDetails" time="1.729">
    <failure type="java.lang.AssertionError" message="correct status code returned expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: correct status code returned expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.qa.test.AutomateApiUsingRestassured.ListsAllCustomerDetails(AutomateApiUsingRestassured.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ListsAllCustomerDetails -->
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsFound1" time="0.061"/>
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsFound2" time="0.022"/>
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsFound3" time="0.018"/>
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsFound4" time="0.013"/>
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsFound5" time="0.015"/>
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsFound6" time="0.014"/>
  <testcase classname="com.qa.test.AutomateApiUsingRestassured" name="CustomerDetailsNotFound" time="0.024"/>
</testsuite> <!-- Default test -->
